### ISSUE TITLE
complete syntax highlighting

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/vscode-reasonml#5]
Remaining tasks:

* Reason
  - classes and objects
    - [ ] `class`
    - [ ] copies
    - [ ] `inherit`
    - [ ] initializers
    - [ ] private methods
    - [ ] recursive classes
    - [ ] self reference
    - [ ] virtual methods
  - patterns
    - [ ] polymorphic variant wildcards
  - terms
    - [ ] coercions
    - [ ] string indexing
  - types
    - [ ] subtyping
* OCaml
  - [ ] `for`
  - [ ] labels
  - [ ] list literals
  - [ ] objects
  - [ ] `while`

**Comment by jmmk** [comment]
Not sure if this fits here or is a separate issue, but it looks like multiline strings aren't supported. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1122242/20366852/ef25c670-ac1a-11e6-8676-a10388c9097f.png)

You can see that not only are the lines of the string not highlighted correctly, but anything immediately following the string is incorrectly highlighted as well (in the second example the `;`, and in the third example the `|> String.uppercase`)

**Comment by freebroccolo** [comment]
@jmmk thanks for reporting this. I've fixed the bug in the string highlighting and pushed a new version to the marketplace.

**Comment by jmmk** [comment]
@freebroccolo looks great, thanks!
