### ISSUE TITLE
Some UTF-8 characters changed into strange code after format

### ISSUE THREAD

**Issue by irrigator** [freebroccolo/vscode-reasonml#51]
For example, after type ```let str = "阳"``` and save, the character 阳 changed into �\152�. I use vim to edit the same file and everything works fine.

Is it the problem with this plugin or merlin?

**Comment by freebroccolo** [comment]
I think this is a known problem with `refmt` which is the upstream binary from the Reason project that handles the reformatting. Might be worth opening an issue for it there if there isn't already one.

**Comment by irrigator** [comment]
thanks. will do.

**Comment by freebroccolo** [comment]
I'm going to close this since it's an upstream issue.
