### ISSUE TITLE
Not recognizing reason language

### ISSUE THREAD

**Issue by AbsoluteZero273** [freebroccolo/vscode-reasonml#52]
![](https://cdn.discordapp.com/attachments/235941706116235276/302811504263168001/2017-04-15-200932_434x544_scrot.png)
What is it I am missing here?
I think it is parsing in OCaml instead.

**Comment by freebroccolo** [comment]
I'm not sure what is causing that without more information about how your project is set up. Do you have merlin installed local to the project?

**Comment by AbsoluteZero273** [comment]
I have following settings set up in user settings 
```
   "reason.path.ocamlmerlin": "/home/absolutezero/.opam/4.03.0/bin/ocamlmerlin",
    "reason.path.refmt": "/home/absolutezero/.opam/4.03.0/bin/refmt",
    "reason.path.rtop": "/home/absolutezero/.opam/4.03.0/bin/rtop",
    "reason.formatOnSave": true
```

**Comment by AbsoluteZero273** [comment]
How do I install merlin locally to the project?

**Comment by AbsoluteZero273** [comment]
I cloned this project: https://github.com/reasonml/ReasonNativeProject
It already has `.merlin`.

**Comment by freebroccolo** [comment]
> I cloned this project: https://github.com/reasonml/ReasonNativeProject
> It already has .merlin.

Can you try unsetting the user settings you mentioned above? As long as your `PATH` is set up correctly you shouldn't need to use them unless you have some custom versions or something. If you don't override them, the reason mode should use the `ocamlmerlin` binary that is installed when you set up the dependencies with npm or whatever.

**Comment by AbsoluteZero273** [comment]
I get the following error when I unset those settings
![2017-04-16-065619_883x75_scrot](https://cloud.githubusercontent.com/assets/16974688/25067938/41e030b2-2272-11e7-87e0-5e181fbd2307.png)

```
/home/absolutezero/.vscode/extensions/freebroccolo.reasonml-0.0.99/node_modules/ocaml-language-server/out/src/server/processes/merlin.js:25
                throw error;
                ^

Error: spawn ocamlmerlin ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 6:58:42 AM] Connection to server got closed. Server will not be restarted.
```
But `ocamlmerlin` should be in PATH as 
```
$ which ocamlmerlin
/home/absolutezero/.opam/4.03.0/bin/ocamlmerlin
```

**Comment by freebroccolo** [comment]
How do you have your shell environment setup? How did you install opam? For whatever reason, when node tries to spawn `ocamlmerlin`, the binary is not in the path.

**Comment by AbsoluteZero273** [comment]
I installed opam with what opam's website instructs to do.
```
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
```

 And for `reason`, I installed it with `opam install reason`.

**Comment by freebroccolo** [comment]
Maybe opam is not being initialized properly (and thus not setting the path) for new shells in some cases. Do you get the same output from the following commands?

`sh -c opam`
`sh -cl opam`

**Comment by AbsoluteZero273** [comment]
Yes

**Comment by freebroccolo** [comment]
Oops, those commands should have run `ocamlmerlin` instead of `opam`. Can you try that? It probably won't make a difference but still…

I think the opam installer script should have either modified one of your shell init scripts or asked you to modify it manually. Do you see that somewhere in like `~/.profile` or `~/.bash_profile` or maybe one of the zsh files if you use that?

The only thing I can really think of is that there's some sort of misconfiguration with how the shell is initializing the opam stuff but it's hard to pinpoint from a distance.

**Comment by AbsoluteZero273** [comment]
`sh -c ocamlmerlin` runs off. But the other one:
```
$ sh -cl ocamlmerlin
sh: ocamlmerlin: command not found
```
Also in my `.zshrc`, the following line has been added.
``` 
. /home/absolutezero/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
```

**Comment by freebroccolo** [comment]
> . /home/absolutezero/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

It's a long shot but you could try moving this to `~/.zshenv` instead and seeing if that helps. I think with `~/.zshrc`, opam may only be initializing the path for login shells which could explain why it's failing for node but not when you try it manually.

**Comment by AbsoluteZero273** [comment]
Not working :slightly_frowning_face:

**Comment by AbsoluteZero273** [comment]
The problem turned out to be the environment (I opened `vscode` with `dmenu`) `vscode` was running on did not have them on PATH. Everything works fine when I opened `vscode` from the terminal. Thanks for taking your time.
