### ISSUE TITLE
question: how to utilize reason.path.rtop?

### ISSUE THREAD

**Issue by desmond-dsouza** [freebroccolo/vscode-reasonml#59]
Great plugin!!

I assume reason.path.rtop is to hook VSCode / ReasonML to REPL functionality, and set it to my rtop, but cannot  figure out how to use it. Could not find suitable forum to ask this question ...

**Comment by freebroccolo** [comment]
Thanks. At the moment there is no terminal integration so it's really just a placeholder. That will probably change at some point.
