### ISSUE TITLE
How to debug indefinite [loading] status?

### ISSUE THREAD

**Issue by quicksnap** [freebroccolo/vscode-reasonml#65]
I'm playing around with https://github.com/bsansouci/reasonglexampleproject on the branch `bsb-support`. When I boot up VSCode, I see the `[loading]` status forever. No completion or refmt, etc.

I can't find a good way to debug and see what's going on under the hood. Any tips on how to find more info?

**Comment by freebroccolo** [comment]
There should be almost no delay loading the server. If you see `[loading]` for more than a second or two, something is wrong.

Have you run `npm install` in the project directory and made sure that `ocamlmerlin` is somewhere in `node_modules`?

You might try `EDITOR=code npm run editor` and see if that helps.

**Comment by quicksnap** [comment]
It somehow resolved itself. However, I've come across the issue in the past. Is there any way to see what's going wrong?

We can close this out whenever, if you want.

**Comment by freebroccolo** [comment]
One possibility is that if you start the editor before you've installed the dependencies, it may get stuck like you described. There are some changes in the server for the upcoming release that should improve the situation. I'm also going to try and change it to where it will display more information if something fails during initialization.

So if you install new dependencies for the project or something like that, make sure to reload the editor. Selecting "reload window" from the command palette should be enough.
